const WATCHLIST_COLUMNS = {
  "Anime Code": "panel.episode_metadata.series_id",
  "Anime Title": "panel.episode_metadata.series_title",
  "fully_watched": "fully_watched",
  "is_favorite": "is_favorite",
  "never_watched": "never_watched",
  "new": "new",
  "panel.channel_id": "panel.channel_id",
  "panel.description": "panel.description",
  "panel.episode_metadata.SeriesGUID": "panel.episode_metadata.SeriesGUID",
  "panel.episode_metadata.audio_locale": "panel.episode_metadata.audio_locale",
  "panel.episode_metadata.availability_ends": "panel.episode_metadata.availability_ends",
  "panel.episode_metadata.availability_notes": "panel.episode_metadata.availability_notes",
  "panel.episode_metadata.availability_starts": "panel.episode_metadata.availability_starts",
  "panel.episode_metadata.availability_status": "panel.episode_metadata.availability_status",
  "panel.episode_metadata.available_date": "panel.episode_metadata.available_date",
  "panel.episode_metadata.available_offline": "panel.episode_metadata.available_offline",
  "panel.episode_metadata.closed_captions_available": "panel.episode_metadata.closed_captions_available",
  "panel.episode_metadata.duration_ms": "panel.episode_metadata.duration_ms",
  "panel.episode_metadata.eligible_region": "panel.episode_metadata.eligible_region",
  "panel.episode_metadata.episode": "panel.episode_metadata.episode",
  "panel.episode_metadata.episode_air_date": "panel.episode_metadata.episode_air_date",
  "panel.episode_metadata.episode_number": "panel.episode_metadata.episode_number",
  "panel.episode_metadata.extended_maturity_rating.level": "panel.episode_metadata.extended_maturity_rating.level",
  "panel.episode_metadata.extended_maturity_rating.rating": "panel.episode_metadata.extended_maturity_rating.rating",
  "panel.episode_metadata.extended_maturity_rating.system": "panel.episode_metadata.extended_maturity_rating.system",
  "panel.episode_metadata.free_available_date": "panel.episode_metadata.free_available_date",
  "panel.episode_metadata.identifier": "panel.episode_metadata.identifier",
  "panel.episode_metadata.is_clip": "panel.episode_metadata.is_clip",
  "panel.episode_metadata.is_dubbed": "panel.episode_metadata.is_dubbed",
  "panel.episode_metadata.is_mature": "panel.episode_metadata.is_mature",
  "panel.episode_metadata.is_premium_only": "panel.episode_metadata.is_premium_only",
  "panel.episode_metadata.is_subbed": "panel.episode_metadata.is_subbed",
  "panel.episode_metadata.mature_blocked": "panel.episode_metadata.mature_blocked",
  "panel.episode_metadata.premium_available_date": "panel.episode_metadata.premium_available_date",
  "panel.episode_metadata.premium_date": "panel.episode_metadata.premium_date",
  "panel.episode_metadata.season_display_number": "panel.episode_metadata.season_display_number",
  "panel.episode_metadata.season_id": "panel.episode_metadata.season_id",
  "panel.episode_metadata.season_number": "panel.episode_metadata.season_number",
  "panel.episode_metadata.season_sequence_number": "panel.episode_metadata.season_sequence_number",
  "panel.episode_metadata.season_slug_title": "panel.episode_metadata.season_slug_title",
  "panel.episode_metadata.season_title": "panel.episode_metadata.season_title",
  "panel.episode_metadata.sequence_number": "panel.episode_metadata.sequence_number",
  "panel.episode_metadata.series_slug_title": "panel.episode_metadata.series_slug_title",
  "panel.episode_metadata.upload_date": "panel.episode_metadata.upload_date",
  "panel.external_id": "panel.external_id",
  "panel.id": "panel.id",
  "panel.linked_resource_key": "panel.linked_resource_key",
  "panel.promo_description": "panel.promo_description",
  "panel.promo_title": "panel.promo_title",
  "panel.recent_audio_locale": "panel.recent_audio_locale",
  "panel.recent_variant": "panel.recent_variant",
  "panel.slug": "panel.slug",
  "panel.slug_title": "panel.slug_title",
  "panel.streams_link": "panel.streams_link",
  "panel.title": "panel.title",
  "panel.type": "panel.type",
  "playhead": "playhead"
}


const HISTORY_COLUMNS = {
  "Geschaut am": "date_played",
  "Dauer (ms)": "panel.episode_metadata.duration_ms",
  "fully_watched": "fully_watched",
  "id": "id",
  "panel": "panel",
  "panel.channel_id": "panel.channel_id",
  "panel.description": "panel.description",
  "panel.episode_metadata": "panel.episode_metadata",
  "panel.episode_metadata.SeriesGUID": "panel.episode_metadata.SeriesGUID",
  "panel.episode_metadata.ad_breaks": "panel.episode_metadata.ad_breaks",
  "panel.episode_metadata.audio_locale": "panel.episode_metadata.audio_locale",
  "panel.episode_metadata.availability_ends": "panel.episode_metadata.availability_ends",
  "panel.episode_metadata.availability_notes": "panel.episode_metadata.availability_notes",
  "panel.episode_metadata.availability_starts": "panel.episode_metadata.availability_starts",
  "panel.episode_metadata.availability_status": "panel.episode_metadata.availability_status",
  "panel.episode_metadata.available_date": "panel.episode_metadata.available_date",
  "panel.episode_metadata.available_offline": "panel.episode_metadata.available_offline",
  "panel.episode_metadata.closed_captions_available": "panel.episode_metadata.closed_captions_available",
  "panel.episode_metadata.content_descriptors": "panel.episode_metadata.content_descriptors",
  "panel.episode_metadata.duration_ms": "panel.episode_metadata.duration_ms",
  "panel.episode_metadata.eligible_region": "panel.episode_metadata.eligible_region",
  "Episode": "panel.episode_metadata.episode",
  "panel.episode_metadata.episode_air_date": "panel.episode_metadata.episode_air_date",
  "panel.episode_metadata.episode_number": "panel.episode_metadata.episode_number",
  "panel.episode_metadata.extended_maturity_rating": "panel.episode_metadata.extended_maturity_rating",
  "panel.episode_metadata.extended_maturity_rating.level": "panel.episode_metadata.extended_maturity_rating.level",
  "panel.episode_metadata.extended_maturity_rating.rating": "panel.episode_metadata.extended_maturity_rating.rating",
  "panel.episode_metadata.extended_maturity_rating.system": "panel.episode_metadata.extended_maturity_rating.system",
  "panel.episode_metadata.free_available_date": "panel.episode_metadata.free_available_date",
  "panel.episode_metadata.identifier": "panel.episode_metadata.identifier",
  "panel.episode_metadata.is_clip": "panel.episode_metadata.is_clip",
  "panel.episode_metadata.is_dubbed": "panel.episode_metadata.is_dubbed",
  "panel.episode_metadata.is_mature": "panel.episode_metadata.is_mature",
  "panel.episode_metadata.is_premium_only": "panel.episode_metadata.is_premium_only",
  "panel.episode_metadata.is_subbed": "panel.episode_metadata.is_subbed",
  "panel.episode_metadata.mature_blocked": "panel.episode_metadata.mature_blocked",
  "panel.episode_metadata.maturity_ratings": "panel.episode_metadata.maturity_ratings",
  "panel.episode_metadata.premium_available_date": "panel.episode_metadata.premium_available_date",
  "panel.episode_metadata.premium_date": "panel.episode_metadata.premium_date",
  "panel.episode_metadata.season_display_number": "panel.episode_metadata.season_display_number",
  "panel.episode_metadata.season_id": "panel.episode_metadata.season_id",
  "Season": "panel.episode_metadata.season_number",
  "panel.episode_metadata.season_sequence_number": "panel.episode_metadata.season_sequence_number",
  "panel.episode_metadata.season_slug_title": "panel.episode_metadata.season_slug_title",
  "panel.episode_metadata.season_title": "panel.episode_metadata.season_title",
  "panel.episode_metadata.sequence_number": "panel.episode_metadata.sequence_number",
  "panel.episode_metadata.series_id": "panel.episode_metadata.series_id",
  "panel.episode_metadata.series_slug_title": "panel.episode_metadata.series_slug_title",
  "Anime Title": "panel.episode_metadata.series_title",
  "panel.episode_metadata.subtitle_locales": "panel.episode_metadata.subtitle_locales",
  "panel.episode_metadata.upload_date": "panel.episode_metadata.upload_date",
  "panel.episode_metadata.versions": "panel.episode_metadata.versions",
  "panel.external_id": "panel.external_id",
  "Episode Code": "panel.id",
  "panel.images": "panel.images",
  "panel.images.thumbnail": "panel.images.thumbnail",
  "panel.linked_resource_key": "panel.linked_resource_key",
  "panel.promo_description": "panel.promo_description",
  "panel.promo_title": "panel.promo_title",
  "panel.slug": "panel.slug",
  "panel.slug_title": "panel.slug_title",
  "panel.streams_link": "panel.streams_link",
  "panel.title": "panel.title",
  "panel.type": "panel.type",
  "parent_id": "parent_id",
  "parent_type": "parent_type",
  "playhead": "playhead",
}

const CRUNCHYLIST_COLUMNS = {
  "Crunchylist Name": "title",
  "Anime Code": "id",
  "list_id": "list_id",
  "modified_at": "modified_at",
  "panel.channel_id": "panel.channel_id",
  "panel.description": "panel.description",
  "panel.external_id": "panel.external_id",
  "panel.id": "panel.id",
  "panel.linked_resource_key": "panel.linked_resource_key",
  "panel.promo_description": "panel.promo_description",
  "panel.promo_title": "panel.promo_title",
  "panel.rating.1s.displayed": "panel.rating.1s.displayed",
  "panel.rating.1s.percentage": "panel.rating.1s.percentage",
  "panel.rating.1s.unit": "panel.rating.1s.unit",
  "panel.rating.2s.displayed": "panel.rating.2s.displayed",
  "panel.rating.2s.percentage": "panel.rating.2s.percentage",
  "panel.rating.2s.unit": "panel.rating.2s.unit",
  "panel.rating.3s.displayed": "panel.rating.3s.displayed",
  "panel.rating.3s.percentage": "panel.rating.3s.percentage",
  "panel.rating.3s.unit": "panel.rating.3s.unit",
  "panel.rating.4s.displayed": "panel.rating.4s.displayed",
  "panel.rating.4s.percentage": "panel.rating.4s.percentage",
  "panel.rating.4s.unit": "panel.rating.4s.unit",
  "panel.rating.5s.displayed": "panel.rating.5s.displayed",
  "panel.rating.5s.percentage": "panel.rating.5s.percentage",
  "panel.rating.5s.unit": "panel.rating.5s.unit",
  "panel.rating.average": "panel.rating.average",
  "panel.rating.rating": "panel.rating.rating",
  "panel.rating.total": "panel.rating.total",
  "panel.series_metadata.availability_notes": "panel.series_metadata.availability_notes",
  "panel.series_metadata.episode_count": "panel.series_metadata.episode_count",
  "panel.series_metadata.extended_description": "panel.series_metadata.extended_description",
  "panel.series_metadata.extended_maturity_rating.level": "panel.series_metadata.extended_maturity_rating.level",
  "panel.series_metadata.extended_maturity_rating.rating": "panel.series_metadata.extended_maturity_rating.rating",
  "panel.series_metadata.extended_maturity_rating.system": "panel.series_metadata.extended_maturity_rating.system",
  "panel.series_metadata.is_dubbed": "panel.series_metadata.is_dubbed",
  "panel.series_metadata.is_mature": "panel.series_metadata.is_mature",
  "panel.series_metadata.is_simulcast": "panel.series_metadata.is_simulcast",
  "panel.series_metadata.is_subbed": "panel.series_metadata.is_subbed",
  "panel.series_metadata.mature_blocked": "panel.series_metadata.mature_blocked",
  "panel.series_metadata.season_count": "panel.series_metadata.season_count",
  "panel.series_metadata.series_launch_year": "panel.series_metadata.series_launch_year",
  "panel.slug": "panel.slug",
  "panel.slug_title": "panel.slug_title",
  "panel.title": "panel.title",
  "panel.type": "panel.type",
  "panel.episode_metadata.series_id": "panel.episode_metadata.series_id",
  "panel.episode_metadata.series_slug_title": "panel.episode_metadata.series_slug_title",
  "panel.episode_metadata.series_title": "panel.episode_metadata.series_title",
  "panel.episode_metadata.subtitle_locales": "panel.episode_metadata.subtitle_locales",
  "panel.episode_metadata.upload_date": "panel.episode_metadata.upload_date",
  "panel.episode_metadata.versions": "panel.episode_metadata.versions",
  "panel.external_id": "panel.external_id",
  "panel.id": "panel.id",
  "panel.images": "panel.images",
  "panel.images.thumbnail": "panel.images.thumbnail",
  "panel.linked_resource_key": "panel.linked_resource_key",
  "panel.promo_description": "panel.promo_description",
  "panel.promo_title": "panel.promo_title",
  "panel.slug": "panel.slug",
  "panel.slug_title": "panel.slug_title",
  "panel.streams_link": "panel.streams_link",
  "Anime Title": "panel.title",
  "panel.type": "panel.type",
  "parent_id": "parent_id",
  "parent_type": "parent_type",
  "playhead": "playhead"
}

// Mapping between different keys for series --> movies
const movie_keys = { "episode_metadata": "movie_metadata", "series_id": "movie_listing_id", "series_title": "movie_listing_title", "series_slug_title": "movie_listing_slug_title" };